package com.ravenemu.deltaskin

enum class DeltaSkinErrorCode {
    INVALID_EXTENSION,
    ARCHIVE_TOO_LARGE,
    NOT_A_ZIP,
    INVALID_ARCHIVE,
    TOO_MANY_ENTRIES,
    DECOMPRESSED_TOO_LARGE,
    ENTRY_TOO_LARGE,
    MANIFEST_MISSING,
    MANIFEST_DUPLICATE,
    MANIFEST_TOO_LARGE,
    MALFORMED_JSON,
    MISSING_REQUIRED_PROPERTY,
    UNSUPPORTED_CONSOLE,
    PORTRAIT_REPRESENTATION_MISSING,
    RESIZABLE_ASSET_MISSING,
    INVALID_MAPPING_SIZE,
    INVALID_FRAME,
    INVALID_NUMBER,
    UNSAFE_ARCHIVE_PATH,
    SYMBOLIC_LINK,
    NESTED_ARCHIVE,
    PDF_INVALID,
    PDF_MULTIPLE_PAGES,
    IDENTIFIER_ALREADY_INSTALLED,
    STORAGE_INSUFFICIENT,
    STORAGE_ERROR,
}

class DeltaSkinException(
    val code: DeltaSkinErrorCode,
    message: String,
    cause: Throwable? = null,
) : Exception(message, cause)
